name: Run the PHP parser
on:
  workflow_dispatch:
permissions: write-all
env: # Or as an environment variable
      SWEN_KEY: ${{ secrets.SWEN_KEY }}
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: execute regular PHP Script
      run: php -q ./feed.php '&k=${{ secrets.SWEN_KEY }}'
    - name: execute Nepali PHP Script parser
      run: php -q ./sparser.php '&k=${{ secrets.SWEN_KEY }}'
    - name: commit files
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}